### ISSUE TITLE
constant error

### ISSUE THREAD

**Issue by cristopherchavezny** [learn-co-curriculum/swift-structL-lab#3]
I keep getting the following error
"Linker command failed with exit code 1 (use -v to see invocation)

**Comment by JimCampagno** [comment]
I can't re-create this error. I imagine it had something to do with Swift 3 and Xcode 8.

Make sure in the future that you run cmd + u (to build out the test file) or cmd + b (to run a normal build) to see if that solves any of your problems.

@cristopherchavezny
